// RIDE Feature Checklist — Sections 1–9
// item = [name, status, probe, evidence]
// status: ok | partial | missing | na
// probe: "file:path" | "grep:pattern" | "grep:pattern@path" | "none"
export const sections = [
  {
    id: 1,
    title: "Core IDE",
    items: [
      ["Desktop application", "ok", "file:apps/desktop/src/main/index.ts", "src/main/index.ts:39-81 BrowserWindow"],
      ["Windows support", "ok", "grep:nsis@apps/desktop/electron-builder.yml", "electron-builder.yml:22-47"],
      ["macOS support", "ok", "grep:dmg@apps/desktop/electron-builder.yml", "electron-builder.yml:22-47"],
      ["Linux support", "ok", "grep:AppImage@apps/desktop/electron-builder.yml", "electron-builder.yml:22-47"],
      ["Fast startup", "partial", "grep:ready-to-show@apps/desktop/src/main/index.ts", "index.ts:45,63; no explicit fast-start measurement"],
      ["Project creation", "ok", "grep:createProjectFromTemplate", "handlers/workspace.ts:90-104"],
      ["Open existing project", "ok", "grep:openProjectDialog", "handlers/workspace.ts:25-33"],
      ["Recent projects", "partial", "grep:touchRecent", "services/settings.ts:147-154; persisted but no UI list"],
      ["Project switching", "ok", "grep:openProjectDialog@apps/desktop/src/renderer/src/App.tsx", "App.tsx:176"],
      ["Workspace management", "ok", "grep:WorkspaceManager", "services/workspace.ts:29-42"],
      ["Multiple windows", "missing", "none", ""],
      ["Multiple tabs", "ok", "grep:CodeTabs", "packages/ui/src/components/CodeTabs.tsx:20-65"],
      ["Tab pinning", "missing", "none", ""],
      ["Tab closing", "ok", "grep:closeTab", "CodeTabs.tsx:51-60"],
      ["Tab reopening", "missing", "none", ""],
      ["Split editor (vertical/horizontal)", "missing", "none", ""],
      ["Full-screen editor", "missing", "none", ""],
      ["Zen/focus mode", "missing", "none", ""],
      ["Command palette", "partial", "grep:CommandBar", "packages/ui CommandBar.tsx fully built but unreachable — no opener"],
      ["Keyboard shortcuts", "ok", "grep:registerCommand", "packages/ide-core/src/commands.ts:69-121; App.tsx:173-187"],
      ["Shortcut customization", "partial", "grep:rebind", "SettingsModal.tsx:224,726-730 read-only; 'ships with next release'"],
      ["Global search", "missing", "none", ""],
      ["Settings", "ok", "grep:SettingsModal", "services/settings.ts:66-267 full round-trip"],
      ["Themes", "ok", "grep:ride-dark@packages/theme/src", "packages/theme/src/index.ts:202-207"],
      ["Light/dark mode", "ok", "grep:ride-light@packages/theme/src", "theme/index.ts:203-204,288-292"],
      ["Zoom controls", "ok", "grep:uiScale@apps/desktop/src/renderer/src/App.tsx", "App.tsx:124-128"],
      ["Accessibility settings", "partial", "grep:screenReader", "stored/persisted but never consumed"],
    ],
  },
  {
    id: 2,
    title: "File Explorer",
    items: [
      ["File tree", "ok", "grep:FileTree", "packages/ui/src/components/FileTree.tsx:22-99"],
      ["Folder creation", "partial", "grep:createFolder", "handlers/workspace.ts:54-57; IPC only, no UI"],
      ["File creation", "partial", "grep:createFile", "workspace.ts:48-52; agent-only UI"],
      ["Rename", "partial", "grep:renameFile", "workspace.ts:59-62; no UI"],
      ["Delete", "partial", "grep:deleteFile", "workspace.ts:64-71; no UI"],
      ["Move", "missing", "none", ""],
      ["Copy", "missing", "none", ""],
      ["Paste", "missing", "none", ""],
      ["Drag & drop", "missing", "none", ""],
      ["Duplicate", "missing", "none", ""],
      ["Hidden files", "partial", "grep:dotfiles", "workspace.ts:75 always skipped, no toggle"],
      ["File icons", "partial", "grep:FileIcon", "FileTree.tsx:51 single generic icon"],
      ["Folder icons", "ok", "grep:FolderOpen", "FileTree.tsx:79-83"],
      ["Search files", "missing", "none", ""],
      ["File filtering", "missing", "none", ""],
      ["Git status indicators", "ok", "grep:gitStatus", "Sidebar.tsx:14-26; FileTree.tsx:53-62"],
      ["Unsaved-change indicators", "ok", "grep:dirty", "CodeTabs.tsx:48-50"],
      ["Context menu", "missing", "none", ""],
      ["Open in external application", "partial", "grep:showItemInFolder", "handlers/app.ts:20-23; only used in ShareModal"],
      ["File preview", "missing", "none", ""],
      ["Image preview", "missing", "none", ""],
      ["PDF preview", "missing", "none", ""],
      ["Markdown preview", "missing", "none", "Markdown renders only agent chat, not files"],
    ],
  },
  {
    id: 3,
    title: "Code Editor",
    items: [
      ["Syntax highlighting", "ok", "grep:monaco-editor", "EditorPane.tsx:2; Monaco tokenizers bundled"],
      ["IntelliSense/autocomplete", "partial", "grep:ghostText", "EditorPane.tsx:41-95; word-based + AI ghost text, no LSP workers"],
      ["Code formatting", "missing", "none", "formatOnSave setting unconsumed"],
      ["Code folding", "ok", "grep:folding", "EditorPane.tsx:119-133"],
      ["Minimap", "ok", "grep:minimap", "EditorPane.tsx:122"],
      ["Line numbers", "ok", "grep:lineNumbers", "Monaco default"],
      ["Error indicators", "missing", "none", "setDiagnostics never called"],
      ["Warning indicators", "missing", "none", ""],
      ["Bracket matching", "ok", "grep:matchBrackets", "theme/index.ts:327-329"],
      ["Auto-closing brackets", "ok", "grep:autoClosingBrackets", "Monaco default"],
      ["Multi-cursor", "ok", "grep:multiCursor", "Monaco default"],
      ["Find & replace", "ok", "grep:monaco", "Monaco built-in Ctrl+F/Ctrl+H"],
      ["Regex search", "ok", "grep:monaco", "Monaco find-widget regex"],
      ["Go to line", "ok", "grep:monaco", "Monaco built-in Ctrl+G"],
      ["Go to symbol", "missing", "none", ""],
      ["Go to definition", "missing", "none", ""],
      ["Go to reference", "missing", "none", ""],
      ["Rename symbol", "missing", "none", ""],
      ["Refactoring", "missing", "none", ""],
      ["Code actions", "missing", "none", ""],
      ["Quick fixes", "missing", "none", ""],
      ["Import management", "partial", "grep:imports@packages/project-db/src", "workspace.ts:185-198 agent context only"],
      ["Breadcrumbs", "missing", "none", "setting exists, no UI"],
      ["Code outline", "missing", "none", ""],
      ["Selection history", "missing", "none", ""],
      ["Undo/redo", "ok", "none", "Monaco default Ctrl+Z/Y"],
      ["Auto-save", "partial", "grep:autoSave", "setting only; editor saves via button/Ctrl+S"],
      ["Language detection", "ok", "grep:detectLang", "lib/hooks.ts:295-304"],
      ["Multiple programming languages", "ok", "grep:monaco.languages", "~80 language chunks bundled"],
    ],
  },
  {
    id: 4,
    title: "AI Agent",
    items: [
      ["Natural-language coding", "ok", "grep:tool_calls@packages/agent-bridge/src", "agent-bridge/src/index.ts:482-678"],
      ["Create project from prompt", "ok", "grep:product-understanding", "templates/engine/pipeline.ts:82-103"],
      ["Modify project from prompt", "ok", "grep:writeFile@apps/desktop/src/main/services/agentTools.ts", "agentTools.ts:95-130"],
      ["Understand existing project", "ok", "grep:RIDE.md", "handlers/agent.ts:25-90,227-240"],
      ["Multi-file editing", "ok", "grep:iterationLimit", "agent-bridge/index.ts:490; 14 tool iterations"],
      ["Create files", "ok", "grep:writeFile", "agentTools.ts:95-130"],
      ["Delete files", "ok", "grep:deleteFile", "agentTools.ts:95-130"],
      ["Rename files", "ok", "grep:renameFile", "agentTools.ts:95-130"],
      ["Move files", "ok", "grep:renameFile", "rename covers move"],
      ["Read files", "ok", "grep:readFile", "agentTools.ts:89-94"],
      ["Search repository", "ok", "grep:grep@apps/desktop/src/main/services/agentTools.ts", "agentTools.ts:137-188 FTS+grep"],
      ["Run terminal commands", "ok", "grep:agentTools", "agentTools.ts:189-208 bash tool"],
      ["Install dependencies", "ok", "grep:installDependencies", "services/deps.ts:47-65"],
      ["Run application", "ok", "grep:preview@apps/desktop/src/main/services/agentTools.ts", "agentTools.ts:212-224 dev server"],
      ["Run tests", "partial", "none", "only via generic bash; no test runner tool"],
      ["Debug errors", "ok", "grep:fix@apps/desktop/src/renderer/src/components/PreviewPane.tsx", "PreviewPane.tsx:79-82 'Fix dev server errors'"],
      ["Fix errors", "ok", "grep:review@apps/desktop/src/main/services/quinn.ts", "quinn.ts:94-104 self-review pass"],
      ["Browser interaction", "ok", "grep:click@apps/desktop/src/main/services/browserAgent.ts", "browserAgent.ts:80-241"],
      ["Screenshot understanding", "partial", "grep:screenshot@apps/desktop/src/main/services/browserAgent.ts", "capture returns PNG path; image never sent to LLM"],
      ["UI iteration", "ok", "grep:iterate", "agentTools.ts:244-278 write→preview→browser→fix loop"],
      ["Database operations", "partial", "none", "only via bash/MCP, no native DB tool"],
      ["API integration", "partial", "grep:mcp@packages/agent-bridge/src", "agent-bridge:577-614 via MCP/webfetch"],
      ["Git operations", "ok", "grep:stash", "agentTools.ts:290-354"],
      ["Deployment operations", "missing", "none", "no deploy tool; backend deploy disconnected from IDE"],
      ["Autonomous task execution", "ok", "grep:scheduler", "services/scheduler.ts:145-216"],
      ["Task planning", "partial", "grep:planner", "agent-core/src/planner.ts:150-195 deterministic, not LLM"],
      ["Task decomposition", "partial", "grep:planner", "planner.ts:71-84 static step lists"],
      ["Progress tracking", "ok", "grep:step.start", "agent-bridge:537-670; timeline UI"],
      ["Confirmation before destructive actions", "ok", "grep:PolicyEngine", "packages/permissions/src/index.ts:112-146"],
      ["Human approval mode", "ok", "grep:permissionRequest", "agent-bridge:781-810; allow-once/always/deny"],
      ["Autonomous mode", "ok", "grep:autonomous", "handlers/agent.ts:107-109,256"],
      ["Agent cancellation", "ok", "grep:AbortController", "agent-bridge:846-850; Esc/Stop"],
      ["Agent retry", "partial", "none", "re-sends last prompt only; no structured tool retry"],
      ["Agent rollback", "missing", "none", "git checkpoint()/rollback() exist but never called"],
    ],
  },
  {
    id: 5,
    title: "RIDE Local Model",
    items: [
      ["Local inference", "ok", "grep:ollama serve", "services/localAi.ts:23,238-252,307-318"],
      ["CPU mode", "ok", "grep:powerProfile", "localAi.ts:230-236"],
      ["GPU acceleration", "partial", "grep:VRAM", "detected but never configured; no num_gpu"],
      ["Automatic hardware detection", "ok", "grep:systeminformation", "services/hardware.ts:17-70"],
      ["RAM detection", "ok", "grep:si.mem", "hardware.ts:46-53"],
      ["VRAM detection", "ok", "grep:vram", "hardware.ts:46-53"],
      ["Dynamic model configuration", "ok", "grep:tier", "services/router.ts:148-305 5-tier catalog"],
      ["Quantized model", "ok", "grep:Q4_K_M", "contracts:1372-1376"],
      ["Low-memory mode", "ok", "grep:lowMemory", "router.ts:208-218,242-267"],
      ["Thermal-aware inference", "partial", "grep:battery", "localAi.ts:156-188 approximated; no thermal sensing"],
      ["CPU usage limits", "partial", "grep:cpuLoad", "localAi.ts:166-175 pause-only guard"],
      ["GPU usage limits", "missing", "none", ""],
      ["Context management", "ok", "grep:num_ctx", "localAi.ts:228-236,254-269"],
      ["Context compression", "ok", "grep:compactMessages", "agent-core/src/compaction.ts:46-120"],
      ["Long-task memory", "ok", "grep:summaries", "quinn.ts:129-141; project-db persistence"],
      ["Project memory", "ok", "grep:project-memory", "quinn.ts:110-126"],
      ["Semantic retrieval", "partial", "grep:bm25", "project-db:255-279 keyword only; no embeddings"],
      ["RIDE library retrieval", "ok", "grep:SKILL.md", "services/skills.ts:65-94; skill tool"],
      ["Tool calling", "missing", "none", "local /api/chat has no tools field"],
      ["Structured outputs", "missing", "none", ""],
      ["Streaming generation", "ok", "grep:NDJSON", "localAi.ts:257-275"],
      ["Cancellation", "missing", "none", "Stop only resets UI; no AbortSignal"],
      ["Model fallback", "ok", "grep:autoEscalate", "localAi.ts:132-150,382-392"],
      ["Offline mode", "ok", "grep:localOnly", "contracts:410-415; L0 instant replies"],
    ],
  },
  {
    id: 6,
    title: "Knowledge / Component System",
    items: [
      ["UI component library", "ok", "grep:galaxy", ".rides/galaxy/ 3,802 components; vendor/galaxy/"],
      ["Design-system library", "ok", "grep:designSystem", "templates/engine/designSystem.ts:86-120"],
      ["Tailwind knowledge", "ok", "grep:tailwind-4-docs", "skills-lock.json; .rides/skills/"],
      ["React knowledge", "ok", "grep:react@packages/plugins/src", "plugin catalog + react skills"],
      ["Next.js knowledge", "missing", "none", "no Next.js generator or skill"],
      ["Animation library", "ok", "grep:gsap", "motion skills (motion/gsap/lottie)"],
      ["3D library", "ok", "grep:react-three-fiber", "three-js/r3f skills; 3D game scaffold"],
      ["Icons", "ok", "grep:lucide", "registry.ts:42 icon-registry skill"],
      ["Charts", "ok", "grep:charts", "engine/registry.ts:40-56"],
      ["Forms", "ok", "grep:FormField", "components-library.ts:235-427"],
      ["Authentication", "ok", "grep:Clerk", "packages/plugins/src/catalog.ts"],
      ["Authorization", "ok", "grep:rbac", "packages/permissions"],
      ["Database modules", "ok", "grep:sqlite@packages/plugins/src", "plugin catalog DBs + scaffolds"],
      ["Payments", "ok", "grep:Razorpay", "packages/plugins/src/catalog.ts"],
      ["Email", "ok", "grep:Resend", "packages/plugins/src/catalog.ts"],
      ["File upload", "ok", "grep:upload", "registry uploads category"],
      ["Search", "ok", "grep:FTS5", "packages/project-db"],
      ["Notifications", "ok", "grep:Twilio", "packages/plugins/src/catalog.ts"],
      ["Maps", "ok", "grep:maps", "engine/registry.ts"],
      ["Analytics", "ok", "grep:PostHog", "packages/plugins/src/catalog.ts:78-83"],
      ["AI integrations", "ok", "grep:OpenAI", "packages/plugins/src/catalog.ts"],
      ["API integrations", "ok", "grep:stripe", "packages/plugins/src/catalog.ts"],
      ["Testing utilities", "partial", "none", "testing keyword only in planner"],
      ["Security patterns", "ok", "grep:security@packages/plugins/src", "plugin catalog security category"],
      ["SEO patterns", "ok", "grep:seo", "scaffold + SEO skills"],
      ["Accessibility patterns", "ok", "grep:wcag", ".rides/skills/design/accessibility"],
      ["Responsive-design rules", "ok", "grep:responsive-design", ".rides/skills/"],
      ["Performance rules", "partial", "grep:lighthouse", "marketing copy only; no perf skill"],
    ],
  },
  {
    id: 7,
    title: "UI/UX Generation",
    items: [
      ["Design-system selection", "ok", "grep:designSystem", "engine/designSystem.ts:86-120; 13 directions"],
      ["Layout generation", "ok", "grep:editorial", "engine/briefs.ts:49; 6 layout architectures"],
      ["Responsive design", "ok", "grep:breakpoints", "engine/qa.ts:137-146,318-323"],
      ["Mobile-first layouts", "ok", "grep:mobile-first", "scaffold.tsx:3462-3865,8451-8453"],
      ["Desktop layouts", "ok", "grep:dual-pane", "catalog.ts:621-691"],
      ["Tablet layouts", "ok", "grep:tablet", "via responsive classes"],
      ["Typography system", "ok", "grep:typography", "designSystem.ts:63-67,108-113"],
      ["Spacing system", "ok", "grep:spacing", "scaffold.tsx:57-91"],
      ["Color system", "ok", "grep:--accent", "scaffold.tsx:59-72 token palette"],
      ["Component hierarchy", "ok", "grep:StateAwareCard", "components-library.ts:180-230"],
      ["Accessibility", "ok", "grep:alt=", "qa.ts:148-160,325-339 autofix"],
      ["UX rules", "ok", "grep:ux-guidelines", ".rides/skills/"],
      ["Navigation rules", "ok", "grep:floating", "briefs.ts:50 5 nav styles"],
      ["Form UX", "ok", "grep:FormSelect", "components-library.ts:235-427"],
      ["Empty states", "ok", "grep:EmptyState", "components-library.ts:38-230"],
      ["Loading states", "ok", "grep:LoadingState", "components-library.ts:38-230"],
      ["Error states", "ok", "grep:ErrorState", "components-library.ts:38-230"],
      ["Success states", "ok", "grep:SuccessState", "components-library.ts:38-230"],
      ["Toasts", "ok", "grep:toast", "gk-* kit + skills"],
      ["Modals", "ok", "grep:modal", "TemplatePreviewModal/CustomizeTemplateModal"],
      ["Drawers", "partial", "none", "gk kit references only"],
      ["Tooltips", "ok", "grep:tooltip", "gk kit + skills"],
      ["Micro-interactions", "ok", "grep:motion@apps/desktop/src/main/services/templates", "briefs.ts:54-55 4 motion profiles"],
      ["Animations", "ok", "grep:framer", "registry Motion + previews.ts:62-73"],
      ["3D elements", "ok", "grep:three@apps/desktop/src/main/services/templates", "catalog.ts:799-811 3D game scaffold"],
      ["Motion graphics", "ok", "grep:cinematic", "previews.ts:1-16,39-80"],
      ["Advanced backgrounds", "ok", "grep:orb", "previews.ts:57-61"],
      ["Glass effects", "ok", "grep:glass", "designSystem.ts:24 glass direction"],
      ["Custom illustrations", "ok", "grep:procedural", "registry.ts:73 SVG direction"],
      ["Icon systems", "ok", "grep:icon-registry", "skills; one family per project"],
      ["Component consistency", "ok", "grep:section-diversity", "qa.ts:210-226"],
    ],
  },
  {
    id: 8,
    title: "Templates",
    items: [
      ["Website — Home", "ok", "file:apps/desktop/src/main/services/templates/catalog.ts", "catalog.ts:89-278; per-brief heroes"],
      ["Website — About", "ok", "grep:AboutPage", "scaffold.tsx:6129"],
      ["Website — Services", "partial", "none", "agency Services feature only; no dedicated page"],
      ["Website — Pricing", "ok", "grep:PricingPage", "scaffold.tsx:774-776"],
      ["Website — Blog", "ok", "grep:BlogPage", "scaffold.tsx:7791,7860"],
      ["Website — Contact", "ok", "grep:ContactPage", "scaffold.tsx:6201 working form"],
      ["Website — FAQ", "partial", "none", "faq section only, no page"],
      ["Website — Login", "ok", "grep:LoginPage", "scaffold.tsx:6360"],
      ["Website — Signup", "ok", "grep:SignupPage", "scaffold.tsx:6370"],
      ["Website — Dashboard", "ok", "grep:DashboardPage", "scaffold.tsx:6479"],
      ["Website — Settings", "ok", "grep:SettingsPage", "scaffold.tsx:6596"],
      ["Website — 404", "ok", "grep:NotFoundPage", "scaffold.tsx:6431"],
      ["Website — Legal", "ok", "grep:PrivacyPage", "scaffold.tsx:6423-6427"],
      ["SaaS — Landing", "ok", "grep:ai-saas", "catalog.ts:281-299"],
      ["SaaS — Authentication", "ok", "grep:authFlow", "scaffold.tsx:9193-9199"],
      ["SaaS — Onboarding", "partial", "none", "onboarding copy only"],
      ["SaaS — Dashboard", "ok", "grep:DashboardPage", "scaffold.tsx:6479"],
      ["SaaS — Workspace", "ok", "grep:PageShell", "scaffold.tsx:5855,6123"],
      ["SaaS — Billing", "ok", "grep:BillingPage", "scaffold.tsx:6697"],
      ["SaaS — Notifications", "partial", "none", "route exists in social architecture only"],
      ["SaaS — Settings", "ok", "grep:SettingsPage", "scaffold.tsx:6596"],
      ["SaaS — Team management", "ok", "grep:TeamPage", "scaffold.tsx:7114"],
      ["SaaS — Permissions", "partial", "none", "role chips in admin-panel only"],
      ["SaaS — Integrations", "ok", "grep:integrations", "plugin catalog + docs page"],
      ["SaaS — API", "ok", "grep:graphql", "catalog.ts:695-725 REST/GraphQL families"],
      ["SaaS — Admin", "ok", "grep:admin-panel", "catalog.ts:329-341"],
      ["SaaS — Error states", "ok", "grep:ErrorState", "scaffold.tsx:9141"],
      ["Mobile — Splash", "missing", "none", ""],
      ["Mobile — Onboarding", "partial", "none", "copy only"],
      ["Mobile — Login", "ok", "grep:LoginPage", "scaffold.tsx:6360"],
      ["Mobile — Signup", "ok", "grep:SignupPage", "scaffold.tsx:6370"],
      ["Mobile — Home", "ok", "grep:HomePage", "scaffold.tsx:8433"],
      ["Mobile — Navigation", "ok", "grep:tab-bar", "scaffold.tsx:5211 bottom tabs"],
      ["Mobile — Core functionality", "ok", "grep:workouts", "catalog.ts:551-619"],
      ["Mobile — Search", "ok", "grep:ai-search", "product-architecture.ts:415"],
      ["Mobile — Notifications", "ok", "grep:notifications", "product-architecture.ts:373"],
      ["Mobile — Profile", "ok", "grep:profile", "product-architecture.ts:353"],
      ["Mobile — Settings", "ok", "grep:settings", "product-architecture.ts:373"],
      ["Mobile — Permissions", "ok", "grep:offline-state", "scaffold.tsx:9132"],
      ["Mobile — Offline state", "ok", "grep:states.offline", "scaffold.tsx:8773,8974"],
      ["Mobile — Error states", "ok", "grep:NotFoundPage", "scaffold.tsx:9140-9141"],
    ],
  },
  {
    id: 9,
    title: "Preview System",
    items: [
      ["Instant preview", "ok", "grep:devServer", "handlers/preview.ts:9-19 auto-start"],
      ["Desktop preview", "missing", "none", "single iframe, no device emulation"],
      ["Tablet preview", "missing", "none", ""],
      ["Mobile preview", "missing", "none", "device setting unconsumed"],
      ["Responsive simulator", "missing", "none", ""],
      ["Reload", "ok", "grep:frameKey", "PreviewPane.tsx:149"],
      ["Hot reload", "partial", "grep:Hot reload", "PreviewPane.tsx:170-174 cosmetic badge; Vite HMR"],
      ["Console", "partial", "grep:stdout", "PreviewPane.tsx:178-196 dev-server logs, not page console"],
      ["Network inspector", "missing", "none", "no CDP wiring"],
      ["Error overlay", "ok", "grep:errorCount", "BrowserPreview.tsx:91-100"],
      ["Screenshot", "missing", "none", "screenshots=[] hardcoded"],
      ["Share preview", "ok", "grep:ShareModal", "ShareModal.tsx:41-70 URL/QR/ZIP/GitHub"],
      ["Public preview URL", "partial", "grep:8788", "deploy/index.ts:129 localhost only"],
      ["project.ride.in", "missing", "none", "marketing copy only"],
      ["Preview versioning", "ok", "grep:-v<", "deploy/index.ts:115-131 snapshot dirs"],
      ["Preview rollback", "ok", "grep:rollbackDeployment", "deploy/index.ts:294-326"],
      ["Preview resource limits", "partial", "grep:entitlement", "server.ts:304-316; decrementProductStock is no-op"],
    ],
  },
];