// RIDE Feature Checklist — Sections 10–24
export const sections = [
  {
    id: 10,
    title: "Terminal",
    items: [
      ["Integrated terminal", "ok", "grep:xterm", "packages/terminal/src/index.ts:33-47"],
      ["Multiple terminals", "partial", "none", "handler Map supports many but renderer mounts one pane"],
      ["Shell selection", "missing", "none", ""],
      ["Command history", "missing", "none", ""],
      ["Environment variables", "missing", "none", ""],
      ["Working directory", "ok", "grep:cwd", "handlers/terminal.ts:21-22"],
      ["Process management", "ok", "grep:resize", "handlers/terminal.ts:11-38"],
      ["Port detection", "partial", "grep:already in use", "services/preview/devServer.ts:9"],
      ["Port forwarding", "missing", "none", ""],
      ["Package installation", "partial", "grep:npm install", "devServer.ts:67-75 auto-install"],
      ["npm/pnpm/yarn", "partial", "grep:lockfile", "services/deps.ts:16-32"],
      ["Python", "missing", "none", ""],
      ["Git", "ok", "grep:git", "handlers/git.ts; git IPC available"],
      ["Build commands", "partial", "grep:defaultBuildCommand", "setting unused (devServer.ts:77-78)"],
      ["Test commands", "missing", "none", ""],
    ],
  },
  {
    id: 11,
    title: "Debugging",
    items: [
      ["Error detection", "ok", "grep:ERROR_RE", "devServer.ts:9"],
      ["Stack traces", "partial", "grep:stack", "devServer.ts:156-181 raw lines"],
      ["Debugger", "missing", "none", "no CDP/debug adapter"],
      ["Breakpoints", "missing", "none", ""],
      ["Watch variables", "missing", "none", ""],
      ["Call stack", "missing", "none", ""],
      ["Console", "partial", "grep:log tab", "PreviewPane.tsx:178-196 dev-server log tab"],
      ["Runtime errors", "partial", "none", "regex-matched from dev-server only"],
      ["Build errors", "ok", "grep:ELIFECYCLE", "devServer.ts:9"],
      ["Dependency errors", "partial", "grep:could not resolve", "devServer.ts:9,71-74"],
      ["AI automatic debugging", "ok", "grep:ride-debugger", "services/model/index.ts:132-153; bugFix routing"],
      ["Automatic fix suggestions", "ok", "grep:reviewer", "quinn.ts:94-106; agent-core reviewer"],
      ["Error reproduction", "partial", "grep:Reproduce", "planner.ts:72; ad-hoc browser repro"],
      ["Regression testing", "partial", "grep:regression", "scheduler.ts; planner risk strings"],
    ],
  },
  {
    id: 12,
    title: "Testing",
    items: [
      ["Unit testing", "missing", "none", "no runner/discovery integration"],
      ["Integration testing", "missing", "none", ""],
      ["E2E testing", "partial", "grep:browserAgent", "browserAgent.ts:80-241 hidden-window automation"],
      ["Component testing", "missing", "none", ""],
      ["API testing", "missing", "none", "backend exposes no test endpoints"],
      ["AI-generated tests", "partial", "grep:aiTestGeneration", "setting unused; agent can write tests"],
      ["Automatic test execution", "partial", "grep:npm test", "bash tool only; generic"],
      ["Test results", "partial", "grep:test-result", "contracts:927 artifact kind; never produced"],
      ["Coverage", "missing", "none", ""],
      ["Regression tests", "partial", "grep:scheduled", "scheduler.ts re-runs agent prompts"],
      ["Visual testing", "partial", "grep:runVisualQA", "qa.ts:71 autofix + browser screenshot"],
      ["Accessibility testing", "partial", "grep:a11y", "reviewer.ts:27 + qa.ts checks"],
      ["Performance testing", "missing", "none", ""],
    ],
  },
  {
    id: 13,
    title: "Git / GitHub",
    items: [
      ["Git initialization", "ok", "grep:git init", "packages/git/src/index.ts:41 GitEngine.init()"],
      ["Clone repository", "missing", "none", "no IPC channels for clone/pull/push"],
      ["Commit", "ok", "grep:commit", "packages/git/src/index.ts:94"],
      ["Push", "partial", "grep:gh repo create", "services/share.ts:135 gh CLI only"],
      ["Pull", "missing", "none", ""],
      ["Branches", "ok", "grep:branches", "packages/git/src/index.ts:99-107"],
      ["Merge", "missing", "none", ""],
      ["Rebase", "missing", "none", ""],
      ["Diff viewer", "partial", "grep:parseDiff", "packages/git/src/index.ts:74-84; no inline UI"],
      ["Merge conflicts", "partial", "grep:diff-filter=U", "git:54 detected but no resolution UI"],
      ["Staging", "ok", "grep:stage", "packages/git/src/index.ts:86-92"],
      ["Commit history", "ok", "grep:log", "packages/git/src/index.ts:109"],
      ["GitHub authentication", "missing", "none", "providers enabled: false; fake record only"],
      ["GitHub repositories", "missing", "none", ""],
      ["Pull requests", "missing", "none", ""],
      ["Issues", "missing", "none", ""],
      ["GitHub Actions", "missing", "none", ""],
      ["AI commit messages", "missing", "none", "SettingsModal advertises but no generator"],
      ["AI PR descriptions", "missing", "none", ""],
    ],
  },
  {
    id: 14,
    title: "APIs / Integrations",
    items: [
      ["REST APIs", "ok", "grep:rest-api", "catalog.ts:695-725; API families in templates"],
      ["GraphQL", "ok", "grep:graphql", "catalog.ts:695-725"],
      ["Webhooks", "partial", "grep:webhook", "server.ts:229-242 inbound payment webhook only"],
      ["OAuth", "missing", "none", "none — flows absent"],
      ["API keys", "partial", "grep:credential", "vault-backed storage; settings groups"],
      ["Environment variables", "partial", "grep:envVars", "teams/index.ts:733-781 role-gated reveal"],
      ["API testing", "missing", "none", ""],
      ["API documentation", "partial", "grep:docsUrl", "plugins catalog static links"],
      ["MCP", "ok", "grep:Streamable HTTP", "mcpClient.ts:18-129 JSON-RPC 2.0 client"],
      ["MCP server management", "ok", "grep:mcpRegistry", "mcpRegistry.ts:18-166 registry + IPC handlers"],
      ["Third-party integrations", "ok", "grep:plugins/src/catalog", "100+ providers in catalog"],
      ["Database connections", "missing", "none", "Settings/Docker/DB scaffolding only"],
      ["Cloud services", "ok", "grep:DeployTarget", "deploy/index.ts local hosting adapter"],
    ],
  },
  {
    id: 15,
    title: "Authentication & Security",
    items: [
      ["Email authentication", "partial", "grep:registerWithBackend", "auth service TODO stubs; login always fails"],
      ["Password authentication", "partial", "grep:registerWithBackend", "same stub flow"],
      ["Google OAuth", "missing", "none", "providers enabled: false; no clientId/secret"],
      ["GitHub OAuth", "missing", "none", "same; fake ConnectedAccount only"],
      ["Magic links", "missing", "none", ""],
      ["OTP", "ok", "grep:otp", "student.ts L1 email/campus ID OTP"],
      ["Sessions", "missing", "none", "JWT stateless; no sessions table; per-request validation only"],
      ["Roles", "ok", "grep:ROLE_ORDER", "teams/index.ts:14 hierarchy"],
      ["Permissions", "ok", "grep:PermissionGate", "packages/permissions/src/index.ts:35-191"],
      ["RBAC", "ok", "grep:rbac", "permissions PolicyEngine"],
      ["Secret management", "partial", "grep:safeStorage", "credential vault AES-256-GCM; master key plaintext base64"],
      ["Environment isolation", "partial", "grep:localOnly", "privacy.localOnly setting"],
      ["Sandbox", "missing", "none", "security.sandbox flag dead; agent bash runs full commands"],
      ["Code execution isolation", "partial", "grep:sandbox: false", "main/index.ts:57-58"],
      ["Dependency scanning", "missing", "none", "deps.ts only installs; --no-audit disables auditing"],
      ["Security warnings", "missing", "none", ""],
      ["XSS protection", "ok", "grep:contextIsolation", "main/index.ts:57-58 CSP meta"],
      ["CSRF protection", "missing", "none", "cors origin: true reflects any origin"],
      ["SQL injection protection", "ok", "grep:prepared", "db.ts/node:sqlite prepared statements"],
    ],
  },
  {
    id: 16,
    title: "Database",
    items: [
      ["PostgreSQL", "missing", "none", ""],
      ["MySQL", "missing", "none", ""],
      ["SQLite", "ok", "grep:node:sqlite", "project-db/src/index.ts:40-123 IDE internal tables"],
      ["Schema generation", "partial", "grep:migrations", "plugins catalog plugin manifests"],
      ["Migration", "missing", "none", ""],
      ["CRUD generation", "partial", "grep:findById", "plugins scaffold:128-133"],
      ["Database browser", "missing", "none", ""],
      ["Query editor", "missing", "none", ""],
      ["Seed data", "missing", "none", ""],
      ["Backup", "missing", "none", ""],
      ["Restore", "missing", "none", ""],
      ["AI database management", "missing", "none", ""],
    ],
  },
  {
    id: 17,
    title: "Deployment",
    items: [
      ["project.ride.in", "missing", "none", "marketing copy only"],
      ["HTTPS", "missing", "none", ""],
      ["CDN", "missing", "none", ""],
      ["Preview hosting", "partial", "grep:localhost:8788", "deploy/index.ts:41-150 local static server"],
      ["Automatic builds", "ok", "grep:staging", "server.ts:344-361; build upload to staging"],
      ["Versioning", "ok", "grep:-v<", "deploy/index.ts:115-131 version dirs"],
      ["Code export", "ok", "grep:ZIP", "services/share.ts:59-153 ZIP download + GitHub export"],
      ["Self-hosting", "ok", "grep:LocalHosting", "deploy/index.ts:41-150 adapter"],
      ["Connect hosting", "missing", "none", ""],
      ["Environment configuration", "partial", "grep:ENV_SECRET", "teams/index.ts:731-789 AES-XOR encrypted"],
      ["Production build", "partial", "grep:production", "devServer picks build script but not production step"],
      ["Custom domain", "missing", "none", ""],
      ["DNS setup", "missing", "none", ""],
      ["SSL", "missing", "none", ""],
      ["Deployment logs", "ok", "grep:logs", "db.ts:80-103; deploy:279-287 health-check record"],
      ["Rollback", "ok", "grep:rollbackDeployment", "deploy/index.ts:294-326 snapshot restore"],
      ["Deployment history", "ok", "grep:/api/deployments", "server.ts:363-384 GET/:id/logs history"],
    ],
  },
  {
    id: 18,
    title: "Package Management",
    items: [
      ["npm", "ok", "grep:lockfile", "services/deps.ts:16-32"],
      ["pnpm", "ok", "grep:lockfile", "same lockfile detection"],
      ["yarn", "partial", "grep:lockfile", "detect only; install only"],
      ["Python pip", "missing", "none", ""],
      ["Dependency detection", "ok", "grep:lockfile", "same"],
      ["Install packages", "ok", "grep:install", "deps.ts:47-65"],
      ["Update packages", "missing", "none", ""],
      ["Remove packages", "missing", "none", ""],
      ["Version conflict detection", "missing", "none", ""],
      ["Security vulnerability detection", "missing", "none", ""],
    ],
  },
  {
    id: 19,
    title: "Project Memory",
    items: [
      ["Project summary", "missing", "none", ""],
      ["Architecture memory", "missing", "none", ""],
      ["User preferences", "partial", "grep:memoryDecisionLimit", "settings.ts:16 persisted but not injected into project memory"],
      ["Design-system memory", "missing", "none", ""],
      ["Important decisions", "ok", "grep:agent_decisions", "project-db:95,170 table + injected in prompts"],
      ["File relationships", "ok", "grep:findImport", "project-db:75,248 imports table + lookups"],
      ["Dependency map", "ok", "grep:setDeps", "project-db:83,155 deps table + persisted"],
      ["Previous tasks", "ok", "grep:scheduled-tasks", "scheduler.ts:46,156 run history to userData"],
      ["Task summaries", "ok", "grep:kind='summary'", "quinn.ts:129 turn summaries persisted"],
      ["Context compression", "ok", "grep:compactMessages", "compaction.ts:46 keepLast tail + tool-call pair drop"],
      ["Semantic search", "partial", "grep:bm25", "project-db:255-279 FTS5 keyword only; no embeddings"],
      ["Automatic memory pruning", "missing", "none", ""],
      ["Memory reset", "missing", "none", ""],
      ["50k+ context management", "ok", "grep:compactionBudgetTokens", "contracts:400; 128k budget, 20k-char window"],
    ],
  },
  {
    id: 20,
    title: "AI Chat",
    items: [
      ["Wide panel", "ok", "grep:--ride-side-panel-width", "App.tsx:204,258 resizable panel"],
      ["Conversation history", "ok", "grep:sessionHistory", "preload:85 IPC; message list + session list"],
      ["New conversation", "partial", "none", "implicit per send; no explicit New button"],
      ["Rename conversation", "missing", "none", ""],
      ["Delete conversation", "missing", "none", ""],
      ["Search conversations", "missing", "none", ""],
      ["Pin conversation", "missing", "none", ""],
      ["Model/provider status", "ok", "grep:ModelChip", "AgentPanel.tsx:89 badge"],
      ["Agent status", "ok", "grep:Working", "AgentPane.tsx:428 Ready/Working/Failed badge"],
      ["Tool execution display", "ok", "grep:RUNNING", "AgentPane.tsx:150 timeline cards"],
      ["File changes", "ok", "grep:Create file", "AgentPane.tsx:308,331 extracted code blocks"],
      ["Diff preview", "partial", "grep:DiffViewer", "exists in ui pkg but unused in renderer; Sidebar hunk counts only"],
      ["Code blocks", "ok", "grep:fenced", "Markdown.tsx:169 fenced-block renderer"],
      ["Copy code", "ok", "grep:Copy", "Markdown.tsx:185 clipboard button"],
      ["Apply code", "ok", "grep:workspace.createFile", "Markdown.tsx:213 write into workspace"],
      ["Undo changes", "partial", "grep:undoOnlyPaths", "preload:65; git-level only"],
      ["Stop generation", "ok", "grep:Stop", "AgentPane.tsx:375 Esc/Stop button"],
      ["Retry", "ok", "grep:Retry", "AgentPane.tsx:491 inline Retry on failed run"],
      ["Regenerate", "ok", "grep:RefreshCw", "AgentPane.tsx:380 RefreshCw on last message"],
      ["Attach files", "missing", "none", "Paperclip button has NO onClick handler"],
      ["Attach images", "missing", "none", ""],
      ["Mention files", "missing", "none", ""],
      ["Mention folders", "missing", "none", ""],
      ["Context selector", "missing", "none", ""],
      ["Token/context indicator", "ok", "grep:token", "AgentPane.tsx:243,458 prompt/completion counts"],
    ],
  },
  {
    id: 21,
    title: "Collaboration",
    items: [
      ["Team workspace", "ok", "grep:TeamStore", "teams/index.ts:265 CRUD + slug + plan/seat fields"],
      ["Invite members", "ok", "grep:invite", "teams/index.ts:416,474 token invitations 7-day expiry"],
      ["Real-time editing", "missing", "none", "no websocket/push channel; 'real-time' only in marketing copy"],
      ["Presence", "missing", "none", ""],
      ["Comments", "ok", "grep:parentId", "teams/index.ts:667,713 threaded comments"],
      ["Mentions", "missing", "none", ""],
      ["Shared AI context", "ok", "grep:team_ai_context", "teams/index.ts:794 notes CRUD + API routes"],
      ["Permissions", "ok", "grep:ROLE_ORDER", "teams:14,347 admin/owner guards"],
      ["Roles", "ok", "grep:ROLE_ORDER", "same hierarchy"],
      ["Project ownership", "ok", "grep:transferOwnership", "teams:403 updates members + owner_id"],
      ["Activity history", "ok", "grep:team_activity", "teams:248 log + feed endpoint"],
      ["Team billing", "partial", "grep:team_seat", "catalog.ts; no dashboard UI"],
    ],
  },
  {
    id: 22,
    title: "Marketplace",
    items: [
      ["Browse templates", "partial", "grep:listPublishedTemplates", "backend listPublishedTemplates + seeded store; desktop UI only local builtin/user"],
      ["Search", "ok", "grep:LIKE", "marketplace/index.ts:99 title/description LIKE search"],
      ["Categories", "ok", "grep:category", "marketplace:index:95 section+family filters"],
      ["Filters", "ok", "grep:sectionFilter", "TemplateStudio:153 combinable section+category+family"],
      ["Preview", "ok", "grep:previewFor", "handlers/templates.ts:87 HTML preview per template"],
      ["Ratings", "ok", "grep:rating", "marketplace:14 rating/ratingCount stored + star"],
      ["Reviews", "partial", "grep:addReview", "marketplace:195 API route; no desktop UI to submit/view"],
      ["Free templates", "ok", "grep:pricePaise=0", "server.ts:435 free-purchase path"],
      ["Paid templates", "ok", "grep:checkout", "server.ts:430,459 gateway checkout → verify → confirm"],
      ["Creator profiles", "partial", "grep:creatorId", "marketplace:260; no profile page UI"],
      ["Creator dashboard", "partial", "grep:creator/stats", "server.ts:581; no dashboard UI component"],
      ["Upload template", "partial", "grep:createTemplate", "backend pending-review flow; SaveTemplateModal local-only store"],
      ["Versioning", "missing", "none", "version column hardcoded 1.0.0; no update endpoints"],
      ["Sales analytics", "ok", "grep:creatorStats", "marketplace:208 sales, commission, earnings, count"],
      ["Revenue dashboard", "partial", "grep:billing/summary", "server.ts:245 stats endpoints only"],
      ["30% RIDE commission", "ok", "grep:RIDE_COMMISSION_RATE", "marketplace:3; splitPrice split recorded"],
      ["Payouts", "ok", "grep:requestPayout", "marketplace:239 + listCreatorPayouts + payout-sum math"],
      ["Refund system", "partial", "grep:refund", "gateway:146 Razorpay refund; no marketplace endpoint/UI"],
      ["Abuse reporting", "missing", "none", ""],
    ],
  },
  {
    id: 23,
    title: "Analytics",
    items: [
      ["Project analytics", "missing", "none", ""],
      ["Deployment analytics", "partial", "grep:health", "deploy status building|live|failed|rolled_back + health checks"],
      ["Visitors", "missing", "none", ""],
      ["Page views", "missing", "none", ""],
      ["Errors", "missing", "none", ""],
      ["Performance", "missing", "none", ""],
      ["API usage", "missing", "none", ""],
      ["Build time", "missing", "none", ""],
      ["Deployment status", "partial", "grep:rolled_back", "db.ts:86 status"],
      ["DAU", "missing", "none", ""],
      ["WAU", "missing", "none", ""],
      ["MAU", "missing", "none", ""],
      ["Retention", "missing", "none", ""],
      ["Projects/user", "missing", "none", ""],
      ["Build success rate", "missing", "none", ""],
      ["Agent success rate", "missing", "none", ""],
      ["Preview usage", "missing", "none", ""],
      ["Export conversion", "missing", "none", ""],
      ["Marketplace GMV", "missing", "none", ""],
      ["Creator revenue", "partial", "grep:earnings", "server.ts:581-603 creatorStats + payouts"],
      ["Infrastructure cost/user", "missing", "none", ""],
    ],
  },
  {
    id: 24,
    title: "Settings",
    items: [
      ["Account", "partial", "none", "AccountPane exists but auth is non-functional stubs"],
      ["Profile", "partial", "none", ""],
      ["Appearance", "ok", "grep:theme@App.tsx", "App.tsx:45,127 DOM class toggle; theme persist"],
      ["Editor", "partial", "none", "many settings unconsumed (auto-save, breadcrumbs, etc)"],
      ["AI", "ok", "grep:quinn", "quinn.ts:65 consumed in agent loop"],
      ["Agent", "partial", "none", "agentPermission setting; limited consumers"],
      ["Models", "partial", "grep:ModelFallback", "model/index.ts:358-388 CRUD UI but dead feature"],
      ["Local model", "ok", "grep:powerProfile", "localAi.ts:158-279 LocalAiPane UI"],
      ["NVIDIA provider", "partial", "grep:getNvidiaKey", "settings.ts:120-137 key stored but unused in agent path"],
      ["OpenCode provider", "missing", "none", "no integration"],
      ["API keys", "partial", "grep:apiKey", "vault storage"],
      ["MCP", "ok", "grep:mcpServers", "mcpRegistry.ts:22"],
      ["GitHub", "missing", "none", ""],
      ["Git", "partial", "none", "settings UI but unconsumed"],
      ["Terminal", "partial", "none", ""],
      ["Security", "missing", "none", "sandbox toggle unused"],
      ["Privacy", "missing", "none", "localOnly toggle unused"],
      ["Notifications", "missing", "none", ""],
      ["Storage", "missing", "none", ""],
      ["Deployment", "missing", "none", "automaticDeployment toggle unconsumed"],
      ["Domains", "missing", "none", ""],
      ["Billing", "missing", "none", ""],
      ["Team", "missing", "none", ""],
    ],
  },
];