// RIDE Feature Checklist — Sections 25–33
export const sections = [
  {
    id: 25,
    title: "3 AI Provider Architecture",
    items: [
      ["NVIDIA Provider connection", "ok", "grep:nvidia", "packages/desktop/src/main/services/provider/adapters/index.ts:10-18 7 builtin adapters"],
      ["NVIDIA API setup", "partial", "grep:NVIDIA_KEY", "packages/model-router/src/index.ts:8-14 hardcoded key; live in agent path"],
      ["NVIDIA Model selection", "ok", "grep:nvidia models", "router:84-92 task→model routing policy"],
      ["NVIDIA Error handling", "missing", "none", ""],
      ["NVIDIA Rate-limit handling", "missing", "none", ""],
      ["NVIDIA Retry/backoff", "missing", "none", ""],
      ["NVIDIA Usage monitoring", "partial", "grep:getUsage", "agent-bridge:313,869-879 in-memory only"],
      ["OpenCode Backend integration", "missing", "none", ""],
      ["OpenCode Model selection", "missing", "none", ""],
      ["OpenCode Auth", "missing", "none", ""],
      ["OpenCode Streaming", "missing", "none", ""],
      ["OpenCode Tool execution", "missing", "none", ""],
      ["OpenCode Error handling", "missing", "none", ""],
      ["RIDE Local Download model", "partial", "none", "evidence of ollama pull? probe none"],
      ["RIDE Local Installation", "partial", "none", ""],
      ["RIDE Local Hardware detection", "ok", "grep:systeminformation", "hardware.ts:17-70"],
      ["RIDE Local CPU/GPU inference", "ok", "grep:ollama serve", "localAi.ts:23 streaming"],
      ["RIDE Local Memory management", "ok", "grep:num_ctx", "localAi.ts:228-236 context mgmt"],
      ["RIDE Local Thermal controls", "partial", "grep:battery", "localAi.ts:156-188 idle-unload approximated"],
      ["RIDE Local Offline operation", "ok", "grep:localOnly", "contracts:410-415 offline mode default true"],
      ["RIDE Local Model update", "missing", "none", ""],
    ],
  },
  {
    id: 26,
    title: "Developer Experience",
    items: [
      ["Documentation", "partial", "grep:DESIGN.md", "DESIGN.md exists but limited scope"],
      ["API documentation", "missing", "none", ""],
      ["CLI", "missing", "none", ""],
      ["Project CLI", "missing", "none", ""],
      ["RIDE extensions", "partial", "grep:VSIX", "extension/index.ts:408 TODO 'Extract VSIX file (it's a zip)'"],
      ["Plugin system", "ok", "grep:PluginService", "plugins/index.ts:35-235 persisted state + catalog"],
      ["SDK", "missing", "none", ""],
      ["MCP support", "ok", "grep:Streamable HTTP", "mcpClient.ts:18-129 JSON-RPC 2.0"],
      ["Webhooks", "partial", "grep:webhook", "server.ts:229-242 inbound payment webhook"],
      ["Environment management", "partial", "grep:envVars", "teams:733-781 role-gated reveal"],
      ["Logs", "partial", "grep:logs", "deploy db + server health endpoint"],
      ["Diagnostics", "partial", "none", "hardware scan + health checks; no dedicated tool"],
      ["Bug reporting", "missing", "none", ""],
    ],
  },
  {
    id: 27,
    title: "Mobile App Development",
    items: [
      ["React Native", "missing", "none", ""],
      ["Expo", "missing", "none", ""],
      ["Flutter support", "missing", "none", ""],
      ["Navigation", "ok", "grep:tab-bar", "scaffold.tsx:5211 bottom tabs in mobile families"],
      ["Authentication", "ok", "grep:LoginPage", "scaffold.tsx:6360 auth-ready feature flag"],
      ["Push notifications", "missing", "none", ""],
      ["Camera", "missing", "none", ""],
      ["Location", "missing", "none", ""],
      ["Maps", "missing", "none", ""],
      ["Storage", "missing", "none", ""],
      ["Deep links", "missing", "none", ""],
      ["App permissions", "missing", "none", ""],
      ["Android build", "partial", "grep:app_build", "backend sold as product (server.ts:163-164) but no service"],
      ["iOS build configuration", "missing", "none", ""],
      ["App icons", "partial", "grep:manifest", "scaffold.tsx:8453 PWA manifest icons"],
      ["Splash screens", "missing", "none", ""],
      ["Store metadata", "missing", "none", ""],
    ],
  },
  {
    id: 28,
    title: "Web Development",
    items: [
      ["HTML", "ok", "none", "scaffold engine generates real HTML; templates produce real content"],
      ["CSS", "ok", "none", "Tailwind v4 + token system in scaffold"],
      ["JavaScript", "ok", "none", "Vanilla JS in generated apps"],
      ["TypeScript", "ok", "none", "TypeScript throughout; routing, state, etc"],
      ["React", "ok", "grep:react", "catalog family + all stacks React+Vite+Tailwind"],
      ["Next.js", "missing", "none", "no Next.js generator; only React+Vite stacks"],
      ["Vue", "missing", "none", ""],
      ["Svelte", "missing", "none", ""],
      ["Node.js", "ok", "grep:express", "catalog node family APIs"],
      ["Python", "missing", "none", "no Python generator"],
      ["API servers", "ok", "grep:rest-api", "REST/GraphQL families in catalog + docs"],
      ["Full-stack applications", "ok", "grep:fullstack", "scaffold engine produces full-stack"],
      ["SSR", "missing", "none", ""],
      ["SSG", "missing", "none", ""],
      ["SEO", "ok", "grep:meta", "scaffold SEO meta + keywords"],
      ["PWA", "ok", "grep:manifest", "scaffold.tsx:8451-8453 offline + manifest"],
      ["Responsive design", "ok", "grep:breakpoints", "qa.ts:137-146 breakpoints + autofix"],
    ],
  },
  {
    id: 29,
    title: "Performance",
    items: [
      ["Fast startup", "partial", "grep:ready-to-show", "index.ts:46,64 show:false + ready-to-show"],
      ["Lazy loading", "missing", "none", "all panes statically imported; no React.lazy"],
      ["Code splitting", "missing", "none", "no manualChunks / bundle analyzer"],
      ["Memory monitoring", "missing", "none", ""],
      ["CPU monitoring", "missing", "none", ""],
      ["GPU monitoring", "missing", "none", ""],
      ["AI inference monitoring", "ok", "grep:getUsage", "agent-bridge:760-779 token/cost per session"],
      ["Build optimization", "missing", "none", "no manualChunks/minification config beyond defaults"],
      ["Bundle analysis", "missing", "none", ""],
      ["Network optimization", "missing", "none", ""],
      ["Image optimization", "missing", "none", ""],
      ["Lighthouse integration", "missing", "none", "zero; marketing copy only"],
    ],
  },
  {
    id: 30,
    title: "Reliability",
    items: [
      ["Crash recovery", "partial", "grep:disable-gpu", "index.ts:29-34 GPU crash mitigation"],
      ["Auto-save", "missing", "none", "files.autoSave setting only; no timer/implementation"],
      ["Project backup", "missing", "none", ""],
      ["Version history", "partial", "grep:undoOnlyPaths", "git:214-224; git checkpoint never called"],
      ["Rollback", "missing", "none", "git checkpoint()/rollback() never called; deployment rollback backend-only"],
      ["Agent rollback", "missing", "none", ""],
      ["Deployment rollback", "ok", "grep:rollbackDeployment", "deploy/index.ts:294-326 snapshot restore"],
      ["Offline recovery", "missing", "none", "network.offlineMode unused toggle"],
      ["Network retry", "ok", "grep:retry@localAi", "localAi.ts:224-276 up to 2 retries + context shrink"],
      ["API retry", "partial", "grep:retry@agent-bridge", "single retry only on HTTP 429/5xx rejection"],
      ["Rate-limit handling", "partial", "grep:authLimiter", "security.ts:56-76 authLimiter 10/min; apiLimiter defined but unused"],
      ["Error reporting", "missing", "none", "crashReports/telemetry stored but never transmitted"],
      ["Health monitoring", "ok", "grep:/health", "server.ts:77 + deploy health checks"],
    ],
  },
  {
    id: 31,
    title: "Students",
    items: [
      ["Student onboarding", "ok", "grep:campus code", "student.ts:4-89 verification stack email OTP campus code ID"],
      ["Student account", "ok", "grep:daysRemaining", "student.ts:205 status + daysRemaining/expiresSoon"],
      ["Campus verification", "ok", "grep:institutions", "student.ts seeded institutions DB verified domains"],
      ["University workspace", "missing", "none", ""],
      ["Workshops", "missing", "none", ""],
      ["Learning projects", "missing", "none", ""],
      ["Beginner templates", "ok", "grep:starter", "catalog starter/blank templates"],
      ["Hackathon mode", "missing", "none", ""],
      ["Student community", "missing", "none", ""],
      ["Campus ambassadors", "missing", "none", ""],
      ["Certificates", "missing", "none", ""],
      ["Tutorials", "missing", "none", ""],
      ["Project showcase", "missing", "none", ""],
    ],
  },
  {
    id: 32,
    title: "Internationalization",
    items: [
      ["Multiple languages", "missing", "none", "no i18n framework, locale files, or translation catalogs"],
      ["INR", "ok", "grep:INR", "pricing.ts:1-6 regions 'in' | 'intl'"],
      ["USD", "ok", "grep:USD", "pricing.ts:1-6"],
      ["EUR", "missing", "none", ""],
      ["GBP", "missing", "none", ""],
      ["Regional pricing", "partial", "grep:'in' | 'intl'", "pricing.ts:1-6 only INR+USD; no EUR/GBP per-country"],
      ["Local payment methods", "partial", "grep:Razorpay", "gateway default mock; Razorpay INR implemented"],
      ["Tax handling", "partial", "grep:GST", "pricing GST-only 18%; no other country taxes"],
      ["Time zones", "missing", "none", ""],
      ["Regional hosting", "missing", "none", ""],
      ["International domains", "missing", "none", ""],
    ],
  },
  {
    id: 33,
    title: "Monetization",
    items: [
      ["Free ₹0", "ok", "grep:pricePaise=0", "catalog.ts free tier projects"],
      ["Project ₹99/$2", "ok", "grep:99", "pricing.ts:32-36 Developer plan ₹99/$2"],
      ["Marketplace 30%", "ok", "grep:RIDE_COMMISSION_RATE", "marketplace:3 + splitPrice split recorded"],
      ["Teams/Agencies/Enterprise", "ok", "grep:agency", "pricing.ts: custom plans"],
      ["Hosting partners", "missing", "none", ""],
    ],
  },
];