packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - electron
  - node-pty
  - esbuild
  - electron-winstaller
  - tree-sitter-wasms
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  node-pty: true
